WARNING | Incorrect data type for Runner
Traceback (most recent call last):
  File "C:\Users\Александр\PycharmProjects\pythonProject\Home Work(Urban)\tests_12_4.py", line 28, in test_run
    runner = Runner(86167)
             ^^^^^^^^^^^^^
  File "C:\Users\Александр\PycharmProjects\pythonProject\Home Work(Urban)\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
WARNING | Incorrect speed for Runner
Traceback (most recent call last):
  File "C:\Users\Александр\PycharmProjects\pythonProject\Home Work(Urban)\tests_12_4.py", line 18, in test_walk
    runner = Runner("Vasya", -3)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Александр\PycharmProjects\pythonProject\Home Work(Urban)\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -3
